In [1]:
from sklearn.datasets import make_classification
import torch

In [21]:
# Create synthetic classification dataset using sklearn
X,y=make_classification(
    n_samples=1000,
    n_features=2,
    n_informative=2,
    n_redundant=0,
    n_classes=2,
    random_state=42
)

In [22]:
X

array([[-0.99910178, -0.66386   ],
       [ 1.24668618,  1.15359685],
       [ 0.96277683,  0.85939747],
       ...,
       [-0.10126746, -1.59017563],
       [ 0.64376105, -0.78053855],
       [ 0.69852984, -1.27940455]])

In [23]:
print(X.shape)
print(y)
print(type(X))

(1000, 2)
[1 1 1 1 1 1 0 0 0 0 1 1 0 1 1 1 0 1 0 1 1 0 1 0 1 0 1 0 1 0 0 0 1 1 0 0 1
 0 0 1 1 0 1 1 0 1 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 1 0 1 0 0 1 0 1 0 0 1
 0 1 0 0 0 1 1 1 0 1 0 1 1 1 0 0 0 1 1 0 1 1 0 0 1 1 0 0 0 0 1 0 0 1 1 1 0
 0 1 0 0 0 0 0 1 0 0 0 1 1 0 1 0 1 1 0 0 0 1 0 0 1 1 1 1 1 0 0 1 1 1 0 0 1
 0 1 1 1 1 0 1 1 1 1 0 1 0 1 1 0 0 1 0 1 0 1 0 0 0 1 1 0 1 0 1 1 0 1 1 0 0
 0 0 0 1 1 0 0 1 1 0 0 0 0 1 1 0 0 1 1 0 1 0 0 1 1 1 0 0 0 0 0 0 1 0 1 1 1
 1 1 0 1 1 1 1 1 1 0 0 1 1 0 0 1 0 0 0 1 1 1 1 1 0 0 1 0 0 0 1 0 1 0 0 1 0
 0 0 0 0 1 1 1 0 1 0 0 0 0 0 1 1 1 0 0 1 0 1 0 1 0 0 0 1 0 0 1 1 1 0 0 0 0
 1 1 1 0 0 1 1 1 1 1 1 0 1 0 1 0 0 0 1 1 0 0 0 0 0 1 0 1 0 1 0 1 0 0 0 1 0
 0 0 1 1 1 0 1 0 0 1 0 1 0 0 0 0 1 1 1 0 1 0 1 1 1 1 0 1 1 0 1 0 1 1 0 0 1
 1 1 1 1 0 1 1 0 0 1 0 0 1 1 0 1 1 0 0 1 0 1 1 0 1 1 1 0 0 0 0 0 1 0 1 0 1
 0 0 0 1 0 0 1 1 0 0 0 1 0 0 0 1 1 0 0 0 1 1 0 0 1 0 1 1 1 0 1 0 1 0 0 1 1
 0 1 0 1 1 0 0 0 0 1 0 0 0 0 0 1 0 1 0 1 0 1 1 1 1 1 0 1 1 1 0 1 0 0 1 1 1
 1 0 1 1 0 0 0 

In [24]:
#convert into a tensor
X=torch.tensor(X,dtype=torch.float32)
y=torch.tensor(y,dtype=torch.long)
print(type(X))
print(type(y))

<class 'torch.Tensor'>
<class 'torch.Tensor'>


In [25]:
from torch.utils.data import Dataset,DataLoader
class CustomDataset(Dataset):
    def __init__(self,features,labels):
        self.features=features
        self.labels=labels
    def __len__(self):
        return self.features.shape[0]
    def __getitem__(self,index):
        return self.features[index],self.labels[index]



In [26]:
dataset=CustomDataset(X,y)

In [27]:
#lest get some methods values len , specific value 
print(len(dataset))
print(dataset[6])
#we can load the data and fetch the data from dataset 

1000
(tensor([-0.6480, -0.7476]), tensor(0))


In [ ]:
# now load the dataloader
# if __name__ == "__main__": #num_workers only run inside the main other wise will show error
dataloader=DataLoader(dataset,batch_size=20,shuffle=True,num_workers=0,pin_memory=True)
# pin_memory is true then gpu will on and fast the speed

In [38]:
for batch_features,batch_labels in dataloader: # get randomly x , y batch iteratevely
    print(batch_features)
    print(batch_labels)
    print("-"*50)

    


tensor([[ 0.9609, -1.2237],
        [ 0.5753,  0.5870],
        [-0.6631, -0.2166],
        [ 2.6171,  2.5542],
        [ 0.0619,  0.1291],
        [ 1.9191, -1.2470],
        [ 1.0537,  1.6794],
        [ 0.4440,  0.4087],
        [-0.2993,  0.9370],
        [ 0.8183, -0.7736],
        [-1.0316, -1.0731],
        [ 1.1319,  0.8533],
        [ 0.5091, -0.9931],
        [-0.7506, -0.0310],
        [ 0.0759,  1.4648],
        [ 1.2920, -0.3765],
        [-0.0049, -0.1615],
        [ 0.2102, -0.7109],
        [-0.0111,  0.1941],
        [-0.7495, -0.0334]])
tensor([0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0])
--------------------------------------------------
tensor([[ 1.9444,  1.9996],
        [ 0.4426,  1.3367],
        [-1.1744, -1.3615],
        [ 0.3972,  3.3075],
        [-2.2142,  1.7321],
        [-1.6073,  1.5849],
        [-1.0185, -1.4069],
        [-1.9787, -1.8023],
        [ 0.8074, -0.9233],
        [-0.9826, -0.7717],
        [-0.6670, -0.1917],
        [-0