In [4]:
#Create model class 
import torch 
import torch.nn as nn
class Model(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        self.linear=nn.Linear(num_features,1)
        self.sigmoid=nn.Sigmoid()

    def forward(self,features):
        out=self.linear(features)
        out=self.sigmoid(out)
        return out


In [5]:
# create dataset 
features=torch.rand(10,5)
model=Model(features.shape[1])# intialize weights and bias 
pre=model(features)# its a magic method which will call forward method and will give predicted output

In [6]:
print(pre)

tensor([[0.6294],
        [0.5234],
        [0.4963],
        [0.5735],
        [0.5085],
        [0.5977],
        [0.6126],
        [0.5973],
        [0.5622],
        [0.5928]], grad_fn=<SigmoidBackward0>)


In [9]:
# check weights of linear layer
print(model.linear.weight)
print(model.linear.bias)

Parameter containing:
tensor([[ 0.4162, -0.3250, -0.0766,  0.1632, -0.2882]], requires_grad=True)
Parameter containing:
tensor([0.3455], requires_grad=True)


In [13]:
# lets see torch model summary
!pip install torchinfo

In [15]:
from torchinfo import summary
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

## Add dense layer 

In [ ]:
#Create model class 

class Model(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        # self.linear1=nn.Linear(num_features,3) # 5 inputs , 3 output
        # self.relu=nn.ReLU()
        # self.linear2=nn.Linear(3,1) # 3 inputs , 1 output
        # self.sigmoid=nn.Sigmoid()
nn.Sequential
        #use sequence 
        self.network=(
            nn.Linear(num_features,3),
            nn.ReLU(),
            nn.Linear(3,1),
            nn.Sigmoid()

        )

    def forward(self,features):
        # out=self.linear1(features)
        # out=self.relu(out)
        # out=self.linear2(out)
        # out=self.sigmoid(out)
        out=self.network(features)
        return out


In [26]:
model=Model(features.shape[1])
pre=model(features)
print(pre)

tensor([[0.5462],
        [0.4940],
        [0.5370],
        [0.5687],
        [0.6118],
        [0.5258],
        [0.5579],
        [0.5388],
        [0.5670],
        [0.5668]], grad_fn=<SigmoidBackward0>)
