In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder


In [11]:
# link : https://github.com/prashant-kikani/breast-cancer-detection/blob/master/breast-cancer-data.csv
df=pd.read_csv("breast-cancer-data.csv")
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

In [13]:
df.drop(columns=['id',"Unnamed: 32"],inplace=True)

In [14]:
df.shape

(569, 31)

In [15]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [16]:
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

# Scale the data  to send in NN

In [17]:
scaler=StandardScaler()
x_train=scaler.fit_transform(X_train)
x_test=scaler.transform(X_test)

In [18]:
x_train

array([[-1.19897098,  0.46517148, -1.22149853, ..., -1.37210632,
        -0.86850154, -0.19359417],
       [-0.37949871, -0.70719182, -0.42195639, ..., -0.51590272,
         0.18855433, -0.79713037],
       [ 0.43712817, -0.33771975,  0.44910632, ...,  0.97745804,
         1.39124901,  1.11931416],
       ...,
       [ 1.46715929, -0.26903584,  1.4247627 , ...,  1.64655632,
         1.07491525, -0.34230723],
       [-1.3597355 ,  0.40122439, -1.34882996, ..., -0.77597305,
        -0.04008294,  0.43056647],
       [ 0.57655227,  0.33017207,  0.58553285, ...,  0.63382611,
         0.31226902, -0.11815215]])

In [19]:
y_train

425    B
195    B
11     M
492    M
124    B
      ..
376    B
515    B
282    M
66     B
328    M
Name: diagnosis, Length: 455, dtype: object

# Now change label 

In [20]:
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

In [22]:
y_test

array([0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 1, 0])

# Convert Numpy Array to pytorch tensor

In [89]:
x_train_tensor=torch.from_numpy(x_train).to(torch.float32)
x_test_tensor=torch.from_numpy(x_test).to(torch.float32)
y_train_tensor=torch.from_numpy(y_train).to(torch.float32).unsqueeze(1)
y_test_tensor=torch.from_numpy(y_test).to(torch.float32).unsqueeze(1)

In [90]:
x_train_tensor.shape

torch.Size([455, 30])

# Define Model

In [91]:
class MyNN():
    def __init__(self,x):
        self.weights=torch.rand(x.shape[1],1,dtype=torch.float32,requires_grad=True)
        self.bias=torch.zeros(1,dtype=torch.float32,requires_grad=True)
    def forward(self,x):
        y=torch.matmul(x,self.weights)+self.bias
        y_predict=torch.sigmoid(y)
        return y_predict

    #Binanry cross Entrophy
    def binary_cross_entrophy(self,pre,tar):
        epsilon=1e-8   #to avoid log(0) we will create range btw 1e-8 to 1-1e-8
        pre=torch.clamp(pre,epsilon,1-epsilon)
        loss=-(tar*torch.log(pre)+(1-tar)*torch.log(1-pre)).mean()
        return loss




# Training Pipeline

In [94]:
model = MyNN(x_train_tensor)
loss_fn = torch.nn.BCELoss()


lr = 0.01
epochs = 50

for epoch in range(epochs):

    # forward pass
    y_pre = model.forward(x_train_tensor)
    # print(y_pre.shape)
    # print(y_train_tensor.shape)

    # compute loss
    # loss = model.binary_cross_entrophy(y_pre, y_train_tensor)
    loss = loss_fn(y_pre, y_train_tensor)

    # backward pass
    loss.backward()

    # update weights
    with torch.no_grad():
        model.weights -= lr * model.weights.grad
        model.bias    -= lr * model.bias.grad

    # clear gradients
    model.weights.grad.zero_() 
    model.bias.grad.zero_()

    print(f"Epoch {epoch+1}, Loss = {loss.item():.4f}")


Epoch 1, Loss = 0.3816
Epoch 2, Loss = 0.3804
Epoch 3, Loss = 0.3793
Epoch 4, Loss = 0.3781
Epoch 5, Loss = 0.3769
Epoch 6, Loss = 0.3758
Epoch 7, Loss = 0.3746
Epoch 8, Loss = 0.3735
Epoch 9, Loss = 0.3723
Epoch 10, Loss = 0.3712
Epoch 11, Loss = 0.3700
Epoch 12, Loss = 0.3689
Epoch 13, Loss = 0.3678
Epoch 14, Loss = 0.3666
Epoch 15, Loss = 0.3655
Epoch 16, Loss = 0.3644
Epoch 17, Loss = 0.3633
Epoch 18, Loss = 0.3621
Epoch 19, Loss = 0.3610
Epoch 20, Loss = 0.3599
Epoch 21, Loss = 0.3588
Epoch 22, Loss = 0.3577
Epoch 23, Loss = 0.3566
Epoch 24, Loss = 0.3555
Epoch 25, Loss = 0.3544
Epoch 26, Loss = 0.3533
Epoch 27, Loss = 0.3523
Epoch 28, Loss = 0.3512
Epoch 29, Loss = 0.3501
Epoch 30, Loss = 0.3490
Epoch 31, Loss = 0.3480
Epoch 32, Loss = 0.3469
Epoch 33, Loss = 0.3458
Epoch 34, Loss = 0.3448
Epoch 35, Loss = 0.3437
Epoch 36, Loss = 0.3427
Epoch 37, Loss = 0.3416
Epoch 38, Loss = 0.3406
Epoch 39, Loss = 0.3395
Epoch 40, Loss = 0.3385
Epoch 41, Loss = 0.3375
Epoch 42, Loss = 0.3364
E

# Evaluation

In [99]:
with torch.no_grad():
    y_pre=model.forward(x_test_tensor)
print((y_pre>0.5).float())
acc=(y_pre==y_test_tensor).float().mean()
print(f"Accuracy : {acc.item()}")

tensor([[0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
      