In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder


In [2]:
# link : https://github.com/prashant-kikani/breast-cancer-detection/blob/master/breast-cancer-data.csv
df=pd.read_csv("breast-cancer-data.csv")
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

In [4]:
df.drop(columns=['id',"Unnamed: 32"],inplace=True)

In [5]:
df.shape

(569, 31)

In [6]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [7]:
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

# Scale the data  to send in NN

In [8]:
scaler=StandardScaler()
x_train=scaler.fit_transform(X_train)
x_test=scaler.transform(X_test)

In [9]:
x_train

array([[-0.9420495 , -1.67409547, -0.96611872, ..., -1.25795714,
        -1.20075062, -0.99507394],
       [-0.89385401, -0.13469494, -0.79562993, ...,  2.05536512,
         1.94391533,  3.28473875],
       [-0.30133302, -0.17508044, -0.27596701, ...,  1.400095  ,
         1.54672729,  1.98694798],
       ...,
       [-1.83508353,  1.221783  , -1.83577544, ..., -1.73798759,
        -0.0623534 , -0.76564307],
       [ 0.16077666, -0.41264225,  0.12976351, ..., -0.48936737,
         1.07760755, -0.62311784],
       [-0.2899929 ,  2.05800057, -0.32104818, ..., -0.54196933,
        -0.68471892, -1.11094812]])

In [10]:
y_train

296    B
379    M
47     M
202    M
494    B
      ..
479    M
50     B
568    B
447    B
543    B
Name: diagnosis, Length: 455, dtype: object

# Now change label 

In [11]:
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

In [12]:
y_test

array([0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 1])

# Convert Numpy Array to pytorch tensor

In [13]:
x_train_tensor=torch.from_numpy(x_train).to(torch.float32)
x_test_tensor=torch.from_numpy(x_test).to(torch.float32)
y_train_tensor=torch.from_numpy(y_train).to(torch.float32).unsqueeze(1)
y_test_tensor=torch.from_numpy(y_test).to(torch.float32).unsqueeze(1)

In [14]:
x_train_tensor.shape

torch.Size([455, 30])

# Use Dataset and Dataloader

In [15]:
from torch.utils.data import Dataset,DataLoader
class CustomDataset(Dataset):
    def __init__(self,features,labels):
        self.features=features
        self.labels=labels
    def __len__(self):
        return self.features.shape[0]
    def __getitem__(self,index):
        return self.features[index],self.labels[index]



In [17]:
train_dataset=CustomDataset(x_train_tensor,y_train_tensor)
test_dataset=CustomDataset(x_test_tensor,y_test_tensor)

In [18]:
train_dataset[10]

(tensor([ 1.7597,  0.5661,  1.6838,  1.7828, -0.3579,  0.1457,  0.1042,  0.7049,
         -0.6979, -1.0607,  0.5895, -0.5503,  0.6250,  0.6628, -0.2807, -0.3543,
         -0.2801,  0.4637, -0.7528, -0.7559,  1.6409,  0.0960,  1.5745,  1.5650,
          0.0104, -0.1076, -0.0105,  0.9147, -0.4721, -0.9418]),
 tensor([1.]))

In [19]:
# load dataset
train_loader=DataLoader(train_dataset,batch_size=32,shuffle=True)
test_loader=DataLoader(test_dataset,batch_size=32,shuffle=True)

# Define Model

In [20]:
import torch.nn as nn
class MyNN(nn.Module):
    def __init__(self,features):
        super().__init__()
        self.network=nn.Sequential(
            nn.Linear(features,32),
            nn.ReLU(),
            nn.Linear(32,1),
            nn.Sigmoid()
        )
    
    def forward(self,x):
        return self.network(x)
      

   
   




# Training Pipeline

In [21]:
model = MyNN(x_train_tensor.shape[1])
loss_fn = torch.nn.BCELoss()
optim=torch.optim.SGD(model.parameters(),lr=0.01)

epochs=50
for epoch in range(epochs):
    for feature,labels in train_loader:

        # forward pass
        y_pre = model.forward(feature)
        # print(y_pre.shape)
        # print(y_train_tensor.shape)

        # compute loss
        # loss = model.binary_cross_entrophy(y_pre, y_train_tensor)
        loss = loss_fn(y_pre, labels)

        # backward pass
        loss.backward()

        # update weights
        optim.step()

        # clear gradients
        optim.zero_grad()

        print(f"Epoch {epoch+1}, Loss = {loss.item():.4f}")


Epoch 1, Loss = 0.6801
Epoch 1, Loss = 0.6794
Epoch 1, Loss = 0.6791
Epoch 1, Loss = 0.6644
Epoch 1, Loss = 0.6680
Epoch 1, Loss = 0.6854
Epoch 1, Loss = 0.6705
Epoch 1, Loss = 0.6532
Epoch 1, Loss = 0.6364
Epoch 1, Loss = 0.6504
Epoch 1, Loss = 0.6766
Epoch 1, Loss = 0.6432
Epoch 1, Loss = 0.6885
Epoch 1, Loss = 0.6289
Epoch 1, Loss = 0.6440
Epoch 2, Loss = 0.6447
Epoch 2, Loss = 0.6444
Epoch 2, Loss = 0.6146
Epoch 2, Loss = 0.6358
Epoch 2, Loss = 0.5870
Epoch 2, Loss = 0.6342
Epoch 2, Loss = 0.6104
Epoch 2, Loss = 0.5976
Epoch 2, Loss = 0.6146
Epoch 2, Loss = 0.6077
Epoch 2, Loss = 0.5979
Epoch 2, Loss = 0.5812
Epoch 2, Loss = 0.5880
Epoch 2, Loss = 0.5896
Epoch 2, Loss = 0.5445
Epoch 3, Loss = 0.5808
Epoch 3, Loss = 0.5785
Epoch 3, Loss = 0.5700
Epoch 3, Loss = 0.5657
Epoch 3, Loss = 0.5703
Epoch 3, Loss = 0.5642
Epoch 3, Loss = 0.5684
Epoch 3, Loss = 0.5616
Epoch 3, Loss = 0.5804
Epoch 3, Loss = 0.5799
Epoch 3, Loss = 0.5743
Epoch 3, Loss = 0.5384
Epoch 3, Loss = 0.5318
Epoch 3, Lo

# Evaluation

In [22]:
model.eval() #set model to evaluation mode
acc_list=[] # accuracy list
with torch.no_grad():
    for batch_features,batch_labels in test_loader:

        y_pre=model.forward(batch_features)
        y_pre=(y_pre>0.5).float() # convert probibilities to binary prediction
        acc=(y_pre==batch_labels).float().mean()
        acc_list.append(acc)
overall_acc=sum(acc_list)/len(acc_list)
print(f"Accuracy : {overall_acc}")

Accuracy : 0.9626736044883728
