In [1]:
import torch
print(torch.__version__)

2.5.1


In [4]:
if torch.cuda.is_available():
    print("GPU is avalable")
    print(f"Uisng GPU : { torch.cuda.get_device_name (0) }")
else:
    print("GPU is not available")

GPU is avalable
Uisng GPU : NVIDIA GeForce RTX 3050 6GB Laptop GPU


## Creating a Tensor

In [9]:
# create empty tensor just for create memory
a=torch.empty(2,3)
print(a)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [10]:
#check type 
type(a)

torch.Tensor

In [ ]:
# now  using zero 2d tensor 
torch.zeros(2,4) # 2 rows , 4 columns

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [13]:
#using ones in 2d tensors 
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [16]:
#using rand  between o to 1 
print(torch.rand(2,3))
print(torch.rand(2,3)) # but it will give diiferent output each time due to rand 

tensor([[0.2809, 0.8831, 0.4241],
        [0.7172, 0.6860, 0.3124]])
tensor([[0.5474, 0.6029, 0.3983],
        [0.5297, 0.2992, 0.0942]])


In [18]:
# so if we want same rand output when ever we run the rand then we will use manual_seed
torch.manual_seed(100)
print(torch.rand(2,3))


tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])


In [20]:
torch.manual_seed(100)
print(torch.rand(2,3)) # now both output are same due to manual seed

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])


In [22]:
# use tensor 
torch.tensor([[1,2,3],[4,5,6]]) # create 2d tensor 

tensor([[1, 2, 3],
        [4, 5, 6]])

In [24]:
# arrange print from 0 to 10 with specific difference
print( " Using arrage ",torch.arange(0,20,2))

 Using arrage  tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])


In [25]:
# now linespace it is also work as range but it divide into equal parts using given value
print("Using linspace ",torch.linspace(0,20,10))

Using linspace  tensor([ 0.0000,  2.2222,  4.4444,  6.6667,  8.8889, 11.1111, 13.3333, 15.5556,
        17.7778, 20.0000])


In [ ]:
# print idendity matrix 
print("Using eye ",torch.eye(5)) #5*5

Using eye  tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [35]:
# using full we can print same number like in matrix 2d or nd
print("Using full", torch.full((2,5),10)) # 2 rows , 5 columns with 10 value in each cell


Using full tensor([[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]])


# Tensor Shapes

In [36]:
x=torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [37]:
x.shape

torch.Size([2, 3])

In [ ]:
# try to copy dimention of specific tensor like x from above
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [39]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [45]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [52]:
torch.rand_like((x),dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

## Tensor data type

In [40]:
x.dtype

torch.int64

In [42]:
torch.tensor([1.9,2.3,4.5],dtype=torch.int32)

tensor([1, 2, 4], dtype=torch.int32)

In [43]:
torch.tensor([1,2,4],dtype=torch.float32)

tensor([1., 2., 4.])

## Math operations 

In [54]:
# Scaler operations
print(x)
# add
print(x+2)

#substract
print(x-2)

# multiply
print(x*4)

#division
print(x/3)
# int devision (floor value instead of 7/3= 2.3333 we will get 2 only, 7/3=2)
print(x//3)

#mod the  remaining  value after devision 
((x*100)//3) %2

# power
print(x**2)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[3, 4, 5],
        [6, 7, 8]])
tensor([[-1,  0,  1],
        [ 2,  3,  4]])
tensor([[ 4,  8, 12],
        [16, 20, 24]])
tensor([[0.3333, 0.6667, 1.0000],
        [1.3333, 1.6667, 2.0000]])
tensor([[0, 0, 1],
        [1, 1, 2]])
tensor([[ 1,  4,  9],
        [16, 25, 36]])


# Element wise operation

In [55]:
a=torch.tensor([[1,2,3],[4,5,6]])
b=torch.tensor([[1,2,3],[4,5,6]])


In [57]:
#add
print(a+b)

#sub
print(a-b)

#mul
print(a*b)

#div
print(a/b)

#pow
print(a**b)


tensor([[ 2,  4,  6],
        [ 8, 10, 12]])
tensor([[0, 0, 0],
        [0, 0, 0]])
tensor([[ 1,  4,  9],
        [16, 25, 36]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[    1,     4,    27],
        [  256,  3125, 46656]])


In [58]:
c=torch.tensor([1,-2,3,-4])

In [59]:
#absolute value ,apply positive to all
torch.abs(c)


tensor([1, 2, 3, 4])

In [60]:
#apply negative to all
torch.neg(c)

tensor([-1,  2, -3,  4])

In [61]:
d=torch.tensor([1.6,2.5,4.3,2.8,8.4])

In [ ]:
# round 
torch.round(d)

tensor([2., 2., 4., 3., 8.])

In [63]:
# ceil value , top 
torch.ceil(d)


tensor([2., 3., 5., 3., 9.])

In [64]:
#floor
torch.floor(d)

tensor([1., 2., 4., 2., 8.])

In [66]:
# clamp, define range between two number 
torch.clamp(d,min=2,max=4)

tensor([2.0000, 2.5000, 4.0000, 2.8000, 4.0000])

# Reduction operation

In [81]:
e=torch.randint(size=(2,3),low=1,high=10)
e

tensor([[4, 9, 2],
        [6, 7, 1]])

In [82]:
#sum all cells 
print(torch.sum(e))
# summ columns wise
print(torch.sum(e,dim=0))

# summ rows wise
print(torch.sum(e,dim=1))


tensor(29)
tensor([10, 16,  3])
tensor([15, 14])


In [83]:
# mean
print(torch.mean(e,dtype=torch.float32))
#median
print(torch.median(e))
#min
print(torch.min(e))

#max
print(torch.max(e))
#product
print(torch.prod(e))

tensor(4.8333)
tensor(4)
tensor(1)
tensor(9)
tensor(3024)


In [91]:
#sd
print(torch.std(e.float()))
#var
print(torch.var(e.float()))

tensor(3.0605)
tensor(9.3667)


In [ ]:
#argmax it will return index where the values is maximum like in 1d =[4,9,2,6,7,1] will return 1 where we have 9
print(torch.argmax(e))

#argmin
print(torch.argmin(e)) #  in 5 index we have min value 5

tensor(1)
tensor(5)


## Matrix Multiplication

In [96]:
f=torch.randint(size=(2,3),low=1,high=10)
g=torch.randint(size=(3,2),low=1,high=10)
print(f)
print(g)

tensor([[7, 4, 9],
        [3, 7, 6]])
tensor([[7, 4],
        [1, 7],
        [5, 4]])


In [99]:
# matrix multiply
print(torch.matmul(f,g))
#dot product 
print(torch.dot(torch.tensor([1,2]),torch.tensor([3,4])))

tensor([[98, 92],
        [58, 85]])
tensor(11)


In [100]:
h=torch.randint(size=(3,3),low=1,high=10,dtype=torch.float32)
print(h)

tensor([[7., 2., 1.],
        [1., 4., 6.],
        [6., 6., 1.]])


In [101]:
# determinant
print(torch.det(h))

#inverse
print(torch.inverse(h))

tensor(-172.)
tensor([[ 0.1860, -0.0233, -0.0465],
        [-0.2035, -0.0058,  0.2384],
        [ 0.1047,  0.1744, -0.1512]])


# comparision tensor


In [102]:
i=torch.randint(size=(3,3),low=1,high=10,dtype=torch.float32)
j=torch.randint(size=(3,3),low=1,high=10,dtype=torch.float32)
print(i)
print(j)

tensor([[4., 1., 3.],
        [7., 2., 2.],
        [8., 4., 1.]])
tensor([[1., 6., 5.],
        [1., 1., 3.],
        [1., 1., 1.]])


In [103]:
#greater than
print(i>j)
#less than
print(i<j)

#equal
print(i==j)

# not equal
print(i!=j)
# greater equal to
print(i>=j)

# less equal to
print(i<=j)


tensor([[ True, False, False],
        [ True,  True, False],
        [ True,  True, False]])
tensor([[False,  True,  True],
        [False, False,  True],
        [False, False, False]])
tensor([[False, False, False],
        [False, False, False],
        [False, False,  True]])
tensor([[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True, False]])
tensor([[ True, False, False],
        [ True,  True, False],
        [ True,  True,  True]])
tensor([[False,  True,  True],
        [False, False,  True],
        [False, False,  True]])


# Special functions

In [105]:
k=torch.randint(size=(2,3),low=1,high=10)
print(k)

tensor([[2, 7, 4],
        [3, 6, 3]])


In [112]:
#log
print(torch.log(k))
#exp
print(torch.exp(k))
#square
print(torch.sqrt(k))
#sigmoid
print(torch.sigmoid(k))
#sigmoid
print(torch.sigmoid(k))
#softmax
print(torch.softmax(k,dim=0,dtype=torch.float32))
#relu
print(torch.relu(k))

tensor([[0.6931, 1.9459, 1.3863],
        [1.0986, 1.7918, 1.0986]])
tensor([[   7.3891, 1096.6332,   54.5981],
        [  20.0855,  403.4288,   20.0855]])
tensor([[1.4142, 2.6458, 2.0000],
        [1.7321, 2.4495, 1.7321]])
tensor([[0.8808, 0.9991, 0.9820],
        [0.9526, 0.9975, 0.9526]])
tensor([[0.8808, 0.9991, 0.9820],
        [0.9526, 0.9975, 0.9526]])
tensor([[0.2689, 0.7311, 0.7311],
        [0.7311, 0.2689, 0.2689]])
tensor([[2, 7, 4],
        [3, 6, 3]])


# Implace operstion 
when we want to change original tensor after operation 

In [118]:
m=torch.rand(2,3)
n=torch.rand(2,3)
print(m)
print(n)

tensor([[0.9157, 0.3079, 0.6269],
        [0.8277, 0.6594, 0.0887]])
tensor([[0.4890, 0.5887, 0.7340],
        [0.8497, 0.9112, 0.4847]])


In [119]:
m.add_(n)

tensor([[1.4047, 0.8966, 1.3610],
        [1.6774, 1.5705, 0.5734]])

In [120]:
m #see the result update the original m

tensor([[1.4047, 0.8966, 1.3610],
        [1.6774, 1.5705, 0.5734]])

In [ ]:
# we cannot use in relu 
o=torch.rand(2,3)
print(o)
print(torch.relu(o))
print(o) # no effect  in original o tensor 

# now we will use implace method 
print(o.relu_())
print(o) # now changes apply in real o

tensor([[0.6688, 0.2651, 0.2336],
        [0.5057, 0.5688, 0.0634]])
tensor([[0.6688, 0.2651, 0.2336],
        [0.5057, 0.5688, 0.0634]])
tensor([[0.6688, 0.2651, 0.2336],
        [0.5057, 0.5688, 0.0634]])
tensor([[0.6688, 0.2651, 0.2336],
        [0.5057, 0.5688, 0.0634]])
tensor([[0.6688, 0.2651, 0.2336],
        [0.5057, 0.5688, 0.0634]])


# Copying a Tensor 

In [124]:
p=torch.rand(2,3)
q=torch.rand(2,3)
print(p)
print(q)

tensor([[0.9556, 0.9761, 0.5934],
        [0.3124, 0.9431, 0.8519]])
tensor([[0.9815, 0.1132, 0.4783],
        [0.4436, 0.3847, 0.4521]])


In [126]:
# we cannot use = sign for copy bcz then they will use same id reference if we apply chages on one tensor it will reflect in other to 
r=q
r[0][0]=0
print(r)
print(q)
print(id(r))
print(id(q))

tensor([[0.0000, 0.1132, 0.4783],
        [0.4436, 0.3847, 0.4521]])
tensor([[0.0000, 0.1132, 0.4783],
        [0.4436, 0.3847, 0.4521]])
2374127052624
2374127052624


In [127]:
# So we will use clone for copy 
s=q.clone()
print(id(s))
print(id(q))

2374130407184
2374127052624


# Tensor Operation on GPU

In [128]:
# check gpu available ?
print(torch.cuda.is_available())

True


In [133]:
#create device
device=torch.device('cuda')
t=torch.rand((2,3),device=device)
# creating a new tensor on GPU
print(t)

tensor([[0.8344, 0.7001, 0.5361],
        [0.8883, 0.0220, 0.7938]], device='cuda:0')


In [137]:
# moving existing tensor to GPU
v=s.to(device)
print(t)
print(v)

# now automatically each operation will use gpu like
print(t+v)

tensor([[0.8344, 0.7001, 0.5361],
        [0.8883, 0.0220, 0.7938]], device='cuda:0')
tensor([[0.0000, 0.1132, 0.4783],
        [0.4436, 0.3847, 0.4521]], device='cuda:0')
tensor([[0.8344, 0.8133, 1.0144],
        [1.3320, 0.4067, 1.2459]], device='cuda:0')


In [181]:
# Compare bwt CPU vs GPU woth time 
import time

size=1000
m1_cpu=torch.rand(size,size)
m2_cpu=torch.rand(size,size)

# time measure
start_time=time.time()

result_cpu=torch.matmul(m1_cpu,m2_cpu)
cpu_time=time.time()-start_time

print("Time on cpu", cpu_time)

# device=torch.device('cuda')
m1_gpu=m1_cpu.to('cuda')
m2_gpu=m2_cpu.to('cuda')
# time measure
start_time=time.time()

result_gpu=torch.matmul(m1_gpu,m2_gpu)
torch.cuda.synchronize()
gpu_time=time.time()-start_time

print("Time on gpu", gpu_time)

print("speed up " ,cpu_time/gpu_time)


Time on cpu 0.022887706756591797
Time on gpu 0.006147146224975586
speed up  3.723306054376915


# Reshaping Tensor

In [183]:
a=torch.rand(4,4)
print(a)

tensor([[0.8280, 0.6489, 0.0328, 0.4012],
        [0.8239, 0.9270, 0.7779, 0.3128],
        [0.0920, 0.5276, 0.6065, 0.9919],
        [0.4229, 0.6947, 0.9879, 0.7680]])


In [186]:
#reshape , convert 16 cells  into diffrent shape but all have 16 values when mutiply diff dimention it should be 16
print(a.reshape(2,2,2,2)) # this we will use in batches, width , hight , channel
print(a.reshape(2,8))
print(a.reshape(8,2))
print(a.reshape(8,-1))


tensor([[[[0.8280, 0.6489],
          [0.0328, 0.4012]],

         [[0.8239, 0.9270],
          [0.7779, 0.3128]]],


        [[[0.0920, 0.5276],
          [0.6065, 0.9919]],

         [[0.4229, 0.6947],
          [0.9879, 0.7680]]]])
tensor([[0.8280, 0.6489, 0.0328, 0.4012, 0.8239, 0.9270, 0.7779, 0.3128],
        [0.0920, 0.5276, 0.6065, 0.9919, 0.4229, 0.6947, 0.9879, 0.7680]])
tensor([[0.8280, 0.6489],
        [0.0328, 0.4012],
        [0.8239, 0.9270],
        [0.7779, 0.3128],
        [0.0920, 0.5276],
        [0.6065, 0.9919],
        [0.4229, 0.6947],
        [0.9879, 0.7680]])
tensor([[0.8280, 0.6489],
        [0.0328, 0.4012],
        [0.8239, 0.9270],
        [0.7779, 0.3128],
        [0.0920, 0.5276],
        [0.6065, 0.9919],
        [0.4229, 0.6947],
        [0.9879, 0.7680]])


In [ ]:
# flatten
print(torch.flatten(a)) # 1d array

tensor([0.8280, 0.6489, 0.0328, 0.4012, 0.8239, 0.9270, 0.7779, 0.3128, 0.0920,
        0.5276, 0.6065, 0.9919, 0.4229, 0.6947, 0.9879, 0.7680])


In [ ]:
b=torch.rand(2,3,4)
print(b.shape) # 3d shape index 0=2, index 1=3, index 2=4 example RGB
print(b)

torch.Size([2, 3, 4])
tensor([[[0.1164, 0.8651, 0.6552, 0.9768],
         [0.7669, 0.6397, 0.8484, 0.4533],
         [0.3324, 0.3759, 0.7615, 0.4173]],

        [[0.2749, 0.3210, 0.5312, 0.4558],
         [0.9729, 0.0043, 0.3687, 0.6277],
         [0.4302, 0.0879, 0.4490, 0.0645]]])


In [ ]:
#permute change index of dimention
c=b.permute(2,0,1) #change index 
print(c.shape)
print(c)


torch.Size([4, 2, 3])
tensor([[[0.1164, 0.7669, 0.3324],
         [0.2749, 0.9729, 0.4302]],

        [[0.8651, 0.6397, 0.3759],
         [0.3210, 0.0043, 0.0879]],

        [[0.6552, 0.8484, 0.7615],
         [0.5312, 0.3687, 0.4490]],

        [[0.9768, 0.4533, 0.4173],
         [0.4558, 0.6277, 0.0645]]])


In [212]:
#unsqeeze , adding new dimetion 
d=torch.rand(226,226,3) #because in DNN model takes baches so we can add dim in 0 index like 
print(d.shape)
d.unsqueeze_(0) #we want to change in original d tensor so we used implace _ , this will be use full
print(d.shape)
d.unsqueeze_(1) #add in 1 index
print(d.shape)
d.unsqueeze_(2)  # add in 2nd index 
print(d.shape)



torch.Size([226, 226, 3])
torch.Size([1, 226, 226, 3])
torch.Size([1, 1, 226, 226, 3])
torch.Size([1, 1, 1, 226, 226, 3])


In [ ]:
#squeeze is opposite of unsqueeze to remove dim
print(d.squeeze_(0).shape)
#squeeze is opposite of unsqueeze to remove dim
print(d.squeeze_(0).shape)
#squeeze is opposite of unsqueeze to remove dim
print(d.squeeze_(0).shape) #now we have original one or  we can we remove channel from tensor like
print(d.squeeze_(2).shape) # this will not work because squeeze mean we can remove only that dimention whi has 1 in their diminton 

torch.Size([1, 1, 226, 226, 3])
torch.Size([1, 226, 226, 3])
torch.Size([226, 226, 3])
torch.Size([226, 226, 3])


In [215]:
print(d.unsqueeze_(2).shape) # add dim in 2 index

print(d.squeeze_(2).shape) # remove from 2 index 

torch.Size([226, 226, 1, 1, 3])
torch.Size([226, 226, 1, 3])


torch.Size([1, 1, 22, 226, 3])
torch.Size([1, 1, 22, 226, 3])


# Numpy and Pytorch

In [219]:
import numpy as np

a=np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [220]:
#convert into a tesnor 

b=torch.from_numpy(a)
print(b)
print(type(b))

tensor([1, 2, 3])
<class 'torch.Tensor'>


In [221]:
#now convert tensor to numpy 
c=b.numpy()
print(c)
print(type(c))

[1 2 3]
<class 'numpy.ndarray'>
